package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/ahmedkhalaf1996/GRQGoTaskx/graph/generated"
	"github.com/ahmedkhalaf1996/GRQGoTaskx/graph/model"
	"github.com/ahmedkhalaf1996/GRQGoTaskx/middleware"
	"github.com/ahmedkhalaf1996/GRQGoTaskx/models"

	"golang.org/x/crypto/bcrypt"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	var getuser models.User
	err := r.DB.First(&getuser, "email = ?", input.Email).Error
	if err == nil {
		return nil, errors.New("email already in used")
	}

	// hashing
	bytePassword := []byte(input.Password)
	passwordHash, err := bcrypt.GenerateFromPassword(bytePassword, bcrypt.DefaultCost)
	if err != nil {
		return nil, errors.New("can't hashed pass something went wrong")
	}

	hashedpassword := string(passwordHash)
	//
	user := &models.User{
		Name:     input.Name,
		Email:    input.Email,
		Password: hashedpassword,
	}

	err = r.DB.Create(&user).Error
	if err != nil {
		return nil, errors.New("can't crate the user")
	}
	// generate token
	token, err := GenToken(user)
	if err != nil {
		log.Printf("error while generating the token: %v", err)
		return nil, errors.New("something went wrong")
	}
	//
	return &model.AuthResponse{
		Authtoken: token,
		User:      user,
	}, nil
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	var user models.User
	err := r.DB.First(&user, "email = ?", input.Email).Error
	if err != nil {
		return nil, errors.New("email not found")
	}

	// compear password
	bytePassword := []byte(input.Password)
	byteHashedPassword := []byte(user.Password)
	err = bcrypt.CompareHashAndPassword(byteHashedPassword, bytePassword)
	if err != nil {
		return nil, errors.New("email/user not correct")
	}

	// generate token
	token, err := GenToken(&user)
	if err != nil {
		log.Printf("error while generating the token: %v", err)
		return nil, errors.New("something went wrong")
	}
	//
	return &model.AuthResponse{
		Authtoken: token,
		User:      &user,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	id, err := middleware.GetCurrentUserFromCTX(ctx)
	if err != nil {
		fmt.Println("not authendicatied me here")
		return nil, errors.New("not authenticated")
	}

	var user models.User
	err = r.DB.First(&user, "id = ?", id).Error
	if err != nil {
		return nil, errors.New("email not found")
	}

	return &user, nil
}

func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return fmt.Sprint(obj.ID), nil
}

func (r *userResolver) Todos(ctx context.Context, obj *models.User) ([]*models.Todo, error) {
	var todos []*models.Todo
	err := r.DB.Find(&todos, "user_id = ?", obj.ID).Select("password").Error
	return todos, err
}

func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
